blog/urls.py
from django.conf.urls import url
from . import views

# ???
app_name = 'blog'
urlpatterns =[
    url(r'^$', views.index, name='index'),
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'', include('comments.urls')),

]

comments/urls.py
from django.conf.urls import url
from . import  views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from  django.utils.six import python_2_unicode_compatible
from django.urls import reverse

# Create your models here.

@python_2_unicode_compatible
class Category(models.Model):
    """
    django 要求我们必须继承 models.Model 类，
    Category 只需要一个简单的分类名 name 就可以了。

    CharField 指定了 name 的数据类型，
    CharField 是字符型，
    max_length 指定其最大长度，
    超过这个长度的分类名就不能被存入数据库。

    当然 django 还为我们提供了各种各样的类型，
    如日期时间类型 DateTimeField、
    整数类型 IntegerField 等等。
    django 内置的类型全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Post(models.Model):
    """
        文章的数据库表稍微复杂一点，主要是涉及的字段更多。
        """
    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。
    # 比较短的字符串存储可以使用 CharField，
    # 但对于文章的正文来说可能会是一大段文本，
    # 因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分表表示了文章的创建时间和最后一次修改时间，
    # 存储时间的列用 DateTimeField。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，
    # 但默认情况下 CharField 要求我们必须存入数据，
    # 否则就会报错。
    # 指定 blank=True 后就可以允许空值了。
    excerpt = models.CharField(max_length=200,blank=True)

    # 这是分类与标签，
    # 分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类与标签对应的表关联起来，
    # 但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，
    # 但是一个分类下可以有很多篇文章，
    # 所以我们使用的是 ForeignKey，
    # 即一对多的关系。
    # 而对于标签来说，
    # 一篇文章可以有多个标签，
    # 同一个标签下也可能有多篇文章，
    # 所以我们使用 ManyToManyField，
    # 表明这是多对多的关系。
    # 同时我们规定文章可以没有标签，
    # 因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，
    # 请看教程中的解释，
    # 亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者
    # 这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，
    # 专门用于处理网站用户的注册、登录等流程，
    # User 是 django 为我们已经写好的用户模型，
    # 这里我们通过 ForeignKey 把文章和 User 关联起来，
    # 因为我们规定一篇文章只能有一个作者，
    # 而一个作者可能会写多篇文章，
    # 因此这是一对多的关系，
    # 和 Category 类似。
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

comments/models.py
from django.db import models
from  django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]
# Create your models here.

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =['name', 'email', 'url', 'text']
        widgets ={
            'name':forms.TextInput(attrs={
                'placeholder': '名字',
            }),
            'email': forms.TextInput(attrs={
                'placeholder':'邮箱',
            }),
            'url': forms.TextInput(attrs ={
                'placeholder':'网址',
            }),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category
import markdown
from comments.forms import CommentForm
# Create your views here.

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', context={'post_list': post_list})
    # return HttpResponse("欢迎访问我的博客首页！")

# 归档视图
def archives(request,year,month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})

# 分类视图
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body =markdown.markdown(post.body, extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite', 'markdown.extensions.toc',])
    form = CommentForm()
    # 获取这篇post下的全部评论
    comment_list = post.comment_set.all()
    context ={
        'post': post,
        'form': form,
        'comment_list': comment_list
        }
    return render(request, 'blog/detail.html', context=context)

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post
from .models import Comment
from .forms import CommentForm


# Create your views here.
def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来
    # 这里我们使用了django提供的一个快捷函数 get_object_or_404
    # 这个函数的作用是当获取的文章（POST）存在时，则获取，否则返回404
    post = get_object_or_404(Post, pk=post_pk)
    #
    # http请求有get和post两种方法，一般用户通过变动提交数据都通过post请求
    # 因此只有当用户的请求为post时才需要处理表单数据
    if request.method == 'POST':

        # 利用这些数据构造了CommentForm的实例，这样django的表单就生成了
        form = CommentForm(request.POST)

        # 当调用form.is_valid()方法时，django自动帮我们检查表单的数据是否符合格式要求
        if form.is_valid():
            # 检查数据是否合法，调用save方法保存数据到数据库
            # commit=False的作用是仅仅利用表单的数据生成Comment的模型类的实例但还不保存到数据库
            comment = form.save(commit=False)
            # 将评论和被评论的文章关联起来
            comment.post = post
            # 最终将评论数据保存到数据库，调用模型实例的save方法
            comment.save()

        else:
            # 检查数据不合法，重新渲染详情页，并且渲染表单的错误
            # 因此我们传了三个模型变量给detali.html,一个是文章（Post），一个是表单 form，一个是评论列表
            # 注意这里我们用到了 post.comment_set.all() 方法,其作用是获取这篇 post 下的的全部评论
            # 因为 Post 和 Comment 是 ForeignKey 关联的， 因此使用 post.comment_set.all() 反向查询全部评论，正向查询就直接是 comment.post
            comment_list = post.comment_set.all()
            context = {
                'post': post,
                'form': form,
                'comment_list': comment_list
            }
            return render(request,'blog/detail.html', context=context)
    # 不是post请求的话，说明用户没有提交评论，重定向到文章详情页
    return redirect(post)

templates/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="href="{% static 'blog/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
		<link rel="stylesheet" href="{% static 'blog/css/friendly.css' %}">

	    <!-- js -->
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'blog/js/pace.min.js' %}"></script>
	    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
		<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
						{% block main %}
                        {% endblock main %}
					</main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">
							<h3 class="widget-title">最新文章</h3>
							{% get_recent_posts as recent_post_list %}
							<ul>
								{% for post in recent_post_list %}
								<li>
									<a href="{{post.get_absolute_url }}">{{post.title }}</a>
								</li>
								{% endfor %}
							</ul>
						</div>
						<div class="widget widget-archives">
							<h3 class="widget-title">归档</h3>
							{% archives as date_list %}
							<ul>
								{% for date in date_list %}
								<li>
									<a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div class="widget widget-category">
							<h3 class="widget-title">分类</h3>
							{% get_categories as category_list %}
							<ul>
								{% for category in category_list %}
								<li>
									<a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
								</li>
								{% endfor %}
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com -More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>

	</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block main%}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>

                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>

                <span class="post-author"><a href="#">{{ post.author }}</a></span>

                <span class="comments-link"><a href="#">4 Comments</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe}}
        </div>
    </article>
    <section class="comment-area">
        <!-- 把友言评论系统代码放到想让评论框显示的地方 -->
        <!-- UY BEGIN -->
        <div id="uyan_frame"></div>
        <script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js?uid=2132282"></script>
<!-- UY END -->
{#    这里第一部分是 自定义的评论系统，不过下面我们选择更人性的有言的第三方账户登录评论#}
{#        <h2>留下你的评论</h2>#}
{#        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">#}
{#          {% csrf_token %}#}
{#          <div class="row">#}
{#            <div class="col-md-4">#}
{#              <label for="{{ form.name.id_for_label }}">Name:</label>#}
{#              {{ form.name }}#}
{#              {{ form.name.errors }}#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#              <label for="{{ form.email.id_for_label }}">Email:</label>#}
{#              {{ form.email }}#}
{#              {{ form.name.errors }}#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#              <label for="{{ form.url.id_for_label }}">Url:</label>#}
{#              {{ form.url }}#}
{#              {{ form.url.errors }}#}
{#            </div>#}
{#            <div class="col-md-12">#}
{#              <label for="{{ form.text.id_for_label }}">Comment:</label>#}
{#              {{ form.text }}#}
{#              {{ form.text.errors }}#}
{#              <button type="submit"><span>发表</span></button>#}
{#            </div>#}
{#          </div>    <!-- row -->#}
{#        </form>#}
{#        <div class="comment-list">#}
{#          <h2>评论列表</h2>#}
{#          <ul class="list-unstyled">#}
{#            {% for comment in comment_list %}#}
{#            <li class="comment-item">#}
{#              <span class="name">{{ comment.name }}</span>#}
{#              <time class="date">{{ comment.created_time }}</time>#}
{#              <div class="text">#}
{#                {{ comment.text }}#}
{#              </div>#}
{#            </li>#}
{#            {% empty %}#}
{#            暂无评论#}
{#            {% endfor %}#}
{#          </ul>#}
{#        </div>#}
    </section>

{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
	{% for post in post_list %}
	<article class="post post-1">
		<header class="entry-header">
			<h1 class="entry-title">
				<a href="{{post.get_absolute_url}}">{{post.title}}</a>
			</h1>
			<div class="entry-meta">
				<span class="post-category"><a href="#">{{post.category.name}}</a></span>

				<span class="post-date"><a href="#"><time class="entry-date" datetime="{{post.created_time}}"></time></a></span>

				<span class="post-author"><a href="#">{{post.author}}</a></span>

				<span class="comments-link"><a href="#">评论 4</a></span>
			</div>
		</header>
		<div class="entry-content clearfix">
			<p>{{ post.excerpt }}</p>
			<div class="read-more cl-effect-14">
				<a href="{{post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
				<!--<a href="https://www.google.com.hk" class="more-link">继续阅读 <span class="meta-nav">→</span></a>-->
			</div>
		</div>
	</article>
	{% empty %}
	  <div class="no-post">暂时还没有发布的文章！</div>
	{% endfor %}
{% endblock main %}